<?php
global $systemProperties;

$systemProperties = array();
$systemProperties['system'] = array();

$systemProperties['system']['isWhiteLabel'] = true;
$systemProperties['system']['partnerFooterUrl'] = '';
$systemProperties['system']['formServicePathURL'] = 'http://forms.yola.com/formservice/';
$systemProperties['system']['ecwidServiceURL'] = 'https://ecwidservice.yola.com/';
$systemProperties['system']['abacusURL'] = '//analytics.yolacdn.net/tracking.js';
$systemProperties['system']['previewNotAllowedURL'] = 'https://www.yola.com/site-not-published';
$systemProperties['system']['purchased'] = array();

$systemProperties['system']['purchased']['yola_footer_removal']['enabled'] = true;
$systemProperties['system']['purchased']['css_overrides']['enabled'] = false;
$systemProperties['system']['purchased']['custom_tracking']['enabled'] = false;

// Ecommerce features
$systemProperties['system']['purchased']['ecommerce']['enabled'] = false;
$systemProperties['system']['purchased']['ecommerce']['storeId'] = '';
$systemProperties['system']['ecwid_api_url'] = '//app.ecwid.com';

$systemProperties['system']['locale'] = 'pt_BR';
$systemProperties['system']['partnerId'] = 'WL_UOLHOST';
$systemProperties['system']['facebookPageId'] = '';

//Define user properties
$systemProperties['system']['user'] = array();
$userProperties =& $systemProperties['system']['user'];
$userProperties['id'] = 'f74359c168d0447caf9c80d692aebe99';
$userProperties['signupDate'] = '2015-01-07 19:35:06';

//Define site properties
$systemProperties['system']['site'] = array();
$siteProperties =& $systemProperties['system']['site'];

$siteProperties['id'] = '8a4986c94ac11584014ac5e5a8a33df5';
$siteProperties['facebookPageId'] = '${facebookPageId}';
$siteProperties['name'] = 'Almeida & Campos Contabilidade';

$systemProperties['system']['template'] = array();
$systemProperties['system']['template']['name'] = 'SuperFlat_v2';
$systemProperties['system']['template']['mobile']['name'] = 'Mobile';

$systemProperties['system']['template']['author'] = array();
$systemProperties['system']['template']['author']['name'] = 'Yola';
$systemProperties['system']['template']['author']['link'] = 'http://www.yola.com';

//Define authentication details
$systemProperties['system']['site']['auth'] = array();
$authDetails =& $systemProperties['system']['site']['auth'];

$authDetails['user'] = '';
$authDetails['pass'] = '';

            $systemProperties['properties']['h6']['text-transform'] = 'none';
                $systemProperties['properties']['button']['small']['letter-spacing'] = '';
                $systemProperties['properties']['h1']['text-transform'] = 'uppercase';
                $systemProperties['properties']['button']['large']['font-weight'] = '';
                $systemProperties['properties']['p']['text-transform'] = 'none';
                $systemProperties['properties']['button']['medium']['padding-left'] = '37px';
                $systemProperties['properties']['button']['large']['font-family'] = '';
                $systemProperties['properties']['nav']['sub-menu-type'] = '';
                $systemProperties['properties']['h1']['text-decoration'] = 'none';
                $systemProperties['properties']['nav']['font-family'] = '\'Open Sans\'';
                $systemProperties['properties']['google']['placesOptIn'] = '';
                $systemProperties['properties']['a:hover']['color'] = '#4d4d4d';
                $systemProperties['properties']['h3']['text-transform'] = 'none';
                $systemProperties['properties']['button']['large']['padding-left'] = '50px';
                $systemProperties['properties']['button']['small']['font-size'] = '12px';
                $systemProperties['properties']['address']['line1'] = 'Rua 233 nº 1487';
                $systemProperties['properties']['footer']['font-weight'] = '';
                $systemProperties['properties']['h4']['color'] = '#4d4d4d';
                $systemProperties['properties']['address']['line2'] = 'Setor Leste Universitário';
                $systemProperties['properties']['button']['small']['padding-left'] = '25px';
                $systemProperties['properties']['mobile']['enabled'] = '';
                $systemProperties['properties']['h4']['font-weight'] = '';
                $systemProperties['properties']['site']['google_fonts'] = '{
 "fonts" : ["Open Sans:regular", "Allerta:regular", "Voltaire:regular"]
}';
                $systemProperties['properties']['h6']['color'] = '#4d4d4d';
                $systemProperties['properties']['heading']['style'] = '';
                $systemProperties['properties']['h2']['font-family'] = '\'Allerta\'';
                $systemProperties['properties']['css']['style-enabled'] = '';
                $systemProperties['properties']['h3']['letter-spacing'] = '2px';
                $systemProperties['properties']['button']['large']['text-transform'] = '';
                $systemProperties['properties']['meta']['googleWebmaster'] = '';
                $systemProperties['properties']['text_widget_mode'] = '';
                $systemProperties['properties']['address']['postal_code'] = '74605120';
                $systemProperties['properties']['h4']['font-size'] = '16px';
                $systemProperties['properties']['p']['letter-spacing'] = '0px';
                $systemProperties['properties']['site']['logo']['width'] = '';
                $systemProperties['properties']['a:link']['color'] = '#1155cc';
                $systemProperties['properties']['nav']['font-weight'] = '';
                $systemProperties['properties']['button']['small']['padding-top'] = '10px';
                $systemProperties['properties']['footer']['text'] = '';
                $systemProperties['properties']['h1']['font-weight'] = '';
                $systemProperties['properties']['tracking']['gaid'] = '';
                $systemProperties['properties']['button']['large']['color'] = '#ffffff';
                $systemProperties['properties']['nav']['text-decoration'] = 'none';
                $systemProperties['properties']['description'] = 'Almeida & Campos Contabilidade';
                $systemProperties['properties']['nav']['color'] = '#ffffff';
                $systemProperties['properties']['h5']['text-decoration'] = 'none';
                $systemProperties['properties']['h6']['font-family'] = '\'Allerta\'';
                $systemProperties['properties']['a:visited']['color'] = '#1155cc';
                $systemProperties['properties']['site']['tagline']['text'] = 'Novos Horizontes Empresariais';
                $systemProperties['properties']['h2']['font-size'] = '24px';
                $systemProperties['properties']['h1']['font-size'] = '70px';
                $systemProperties['properties']['h3']['color'] = '#4d4d4d';
                $systemProperties['properties']['address']['country'] = 'BR';
                $systemProperties['properties']['google']['businessCategories'] = '';
                $systemProperties['properties']['p']['color'] = '#4d4d4d';
                $systemProperties['properties']['nav']['letter-spacing'] = '5px';
                $systemProperties['properties']['h4']['text-transform'] = 'none';
                $systemProperties['properties']['phone']['main'] = '62 - 3218-1907';
                $systemProperties['properties']['h3']['line-height'] = '1.5em';
                $systemProperties['properties']['button']['medium']['font-size'] = '15px';
                $systemProperties['properties']['meta']['favicon'] = '';
                $systemProperties['properties']['h4']['letter-spacing'] = '2px';
                $systemProperties['properties']['tracking']['footer'] = '';
                $systemProperties['properties']['button']['small']['font-weight'] = '';
                $systemProperties['properties']['h2']['text-decoration'] = 'none';
                $systemProperties['properties']['h2']['text-transform'] = 'none';
                $systemProperties['properties']['button']['medium']['letter-spacing'] = '';
                $systemProperties['properties']['h1']['color'] = '#ffffff';
                $systemProperties['properties']['button']['small']['text-transform'] = '';
                $systemProperties['properties']['button']['small']['background-color'] = '#333333';
                $systemProperties['properties']['h6']['text-decoration'] = 'none';
                $systemProperties['properties']['p']['font-size'] = '16px';
                $systemProperties['properties']['h6']['font-weight'] = '';
                $systemProperties['properties']['h6']['font-size'] = '11px';
                $systemProperties['properties']['nav:selected']['color'] = '#ffffff';
                $systemProperties['properties']['h5']['font-family'] = '\'Allerta\'';
                $systemProperties['properties']['sitetemplate'] = 'bc427956-0f3c-4e7f-b453-716c6bf2f3ac';
                $systemProperties['properties']['button']['small']['style'] = 'solid';
                $systemProperties['properties']['a:hover']['text-decoration'] = 'underline';
                $systemProperties['properties']['css']['overrides'] = '';
                $systemProperties['properties']['button']['medium']['background-color'] = '#333333';
                $systemProperties['properties']['h5']['text-transform'] = 'none';
                $systemProperties['properties']['button']['medium']['line-height'] = '';
                $systemProperties['properties']['h2']['color'] = '#4d4d4d';
                $systemProperties['properties']['button']['large']['line-height'] = '';
                $systemProperties['properties']['nav']['line-height'] = '1.5em';
                $systemProperties['properties']['p']['font-family'] = '\'Open Sans\'';
                $systemProperties['properties']['h3']['text-decoration'] = 'none';
                $systemProperties['properties']['address']['city'] = 'Goiânia';
                $systemProperties['properties']['css']['overrides-enabled'] = '';
                $systemProperties['properties']['h5']['font-weight'] = '';
                $systemProperties['properties']['button']['small']['shape'] = 'rounded';
                $systemProperties['properties']['h4']['font-family'] = '\'Allerta\'';
                $systemProperties['properties']['h1']['line-height'] = '1.5em';
                $systemProperties['properties']['h5']['line-height'] = '1.5em';
                $systemProperties['properties']['site']['logo']['src'] = '';
                $systemProperties['properties']['button']['small']['font-family'] = '';
                $systemProperties['properties']['button']['large']['font-size'] = '20px';
                $systemProperties['properties']['h1']['font-family'] = '\'Voltaire\'';
                $systemProperties['properties']['h6']['line-height'] = '1.5em';
                $systemProperties['properties']['nav']['font-size'] = '20px';
                $systemProperties['properties']['style_designer']['enabled'] = '';
                $systemProperties['properties']['h5']['color'] = '#4d4d4d';
                $systemProperties['properties']['button']['large']['letter-spacing'] = '';
                $systemProperties['properties']['h4']['text-decoration'] = 'none';
                $systemProperties['properties']['h6']['letter-spacing'] = '2px';
                $systemProperties['properties']['button']['medium']['font-family'] = '';
                $systemProperties['properties']['h2']['line-height'] = '1.5em';
                $systemProperties['properties']['button']['large']['shape'] = 'rounded';
                $systemProperties['properties']['h5']['font-size'] = '13px';
                $systemProperties['properties']['p']['font-weight'] = '';
                $systemProperties['properties']['button']['small']['color'] = '#ffffff';
                $systemProperties['properties']['button']['large']['style'] = 'solid';
                $systemProperties['properties']['tracking']['header'] = '';
                $systemProperties['properties']['button']['medium']['shape'] = 'rounded';
                $systemProperties['properties']['address']['state'] = 'GO';
                $systemProperties['properties']['site']['tagline']['font-weight'] = '';
                $systemProperties['properties']['h3']['font-family'] = '\'Allerta\'';
                $systemProperties['properties']['a:link']['text-decoration'] = 'none';
                $systemProperties['properties']['nav']['text-transform'] = 'none';
                $systemProperties['properties']['h5']['letter-spacing'] = '2px';
                $systemProperties['properties']['p']['line-height'] = '1.5em';
                $systemProperties['properties']['button']['medium']['padding-top'] = '15px';
                $systemProperties['properties']['button']['large']['background-color'] = '#333333';
                $systemProperties['properties']['button']['small']['line-height'] = '';
                $systemProperties['properties']['button']['medium']['text-transform'] = '';
                $systemProperties['properties']['h4']['line-height'] = '1.5em';
                $systemProperties['properties']['h1']['letter-spacing'] = '30px';
                $systemProperties['properties']['button']['medium']['color'] = '#ffffff';
                $systemProperties['properties']['h3']['font-weight'] = '';
                $systemProperties['properties']['h2']['letter-spacing'] = '2px';
                $systemProperties['properties']['button']['medium']['font-weight'] = '';
                $systemProperties['properties']['h3']['font-size'] = '19px';
                $systemProperties['properties']['nav:hover']['color'] = '#ffffff';
                $systemProperties['properties']['button']['large']['padding-top'] = '20px';
                $systemProperties['properties']['blockquote']['font-weight'] = '';
                $systemProperties['properties']['h2']['font-weight'] = '';
                $systemProperties['properties']['button']['medium']['style'] = 'solid';
                $systemProperties['properties']['css']['fonts'] = '@import url(\'http://fonts.googleapis.com/css?family=Raleway:100|Open+Sans\');.sys_navigation, #sys_heading, div#heading_wrapper a, div#menu ul, H1, H2, H3, H4, H5, H6, #content h1, #content h2, #content h3, #content h4, #content h5, #content h6, #content_wrapper #content_inner_wrapper h1, #content_wrapper #content_inner_wrapper h2, #content_wrapper #content_inner_wrapper h3, #content_wrapper #content_inner_wrapper h4, #headline_wrapper a,div#menu ul li a, a#sys_heading, .decay, .decay-small, .ys_menu_2  {font-family: Raleway;}.content, #content, .HTML_Default, .Text_Default, .sys_txt  {font-family: Open Sans;}';
                $systemProperties['properties']['footer']['display'] = 'block';
                $systemProperties['properties']['footer']['padding-left'] = '60px';
                $systemProperties['properties']['header']['alignment'] = 'top';
                $systemProperties['properties']['banner']['content']['max-width'] = '';
                $systemProperties['properties']['banner']['padding-top'] = '40px';
                $systemProperties['properties']['site']['tagline']['text-transform'] = 'none';
                $systemProperties['properties']['banner']['background-position'] = 'center center';
                $systemProperties['properties']['header']['background-color'] = 'rgba(34,34,34,0.80)';
                $systemProperties['properties']['site']['tagline']['font-size'] = '24px';
                $systemProperties['properties']['blockquote']['font-style'] = 'italic';
                $systemProperties['properties']['body']['padding-bottom'] = '50px';
                $systemProperties['properties']['h1']['text-align'] = 'center';
                $systemProperties['properties']['content']['padding-bottom'] = '40px';
                $systemProperties['properties']['body']['padding-left'] = '0px';
                $systemProperties['properties']['body']['background-attachment'] = 'fixed';
                $systemProperties['properties']['footer']['text-transform'] = 'none';
                $systemProperties['properties']['banner']['src'] = '';
                $systemProperties['properties']['site']['tagline']['padding-top'] = '';
                $systemProperties['properties']['footer']['color'] = '#ffffff';
                $systemProperties['properties']['body']['padding-right'] = '0px';
                $systemProperties['properties']['blockquote']['text-transform'] = '';
                $systemProperties['properties']['body']['background-image'] = 'classes/commons/resources/images/backgrounds/retina_wood.png';
                $systemProperties['properties']['body']['background-repeat'] = 'repeat';
                $systemProperties['properties']['blockquote']['letter-spacing'] = '';
                $systemProperties['properties']['site']['tagline']['line-height'] = '1.5em';
                $systemProperties['properties']['content']['max-width'] = '960px';
                $systemProperties['properties']['site']['tagline']['padding-bottom'] = '';
                $systemProperties['properties']['footer']['padding-bottom'] = '20px';
                $systemProperties['properties']['site']['tagline']['padding-left'] = '';
                $systemProperties['properties']['footer']['font-size'] = '12px';
                $systemProperties['properties']['page']['vertical-align'] = 'top';
                $systemProperties['properties']['content']['background-color'] = 'rgba(255,255,255,1)';
                $systemProperties['properties']['content']['container']['background-color'] = '';
                $systemProperties['properties']['site']['tagline']['letter-spacing'] = '5px';
                $systemProperties['properties']['footer']['padding-top'] = '20px';
                $systemProperties['properties']['content']['padding-left'] = '60px';
                $systemProperties['properties']['blockquote']['background-color'] = '';
                $systemProperties['properties']['body']['background-position'] = 'top left';
                $systemProperties['properties']['banner']['padding-bottom'] = '40px';
                $systemProperties['properties']['site']['tagline']['background-color'] = '';
                $systemProperties['properties']['footer']['line-height'] = '1.5em';
                $systemProperties['properties']['nav']['padding-left'] = '';
                $systemProperties['properties']['banner']['padding-left'] = '60px';
                $systemProperties['properties']['nav']['background-color'] = 'rgba(41,41,41,1)';
                $systemProperties['properties']['site']['tagline']['font-family'] = '\'Open Sans\'';
                $systemProperties['properties']['body']['foreground-color'] = '';
                $systemProperties['properties']['blockquote']['line-height'] = '';
                $systemProperties['properties']['site']['tagline']['text-align'] = '';
                $systemProperties['properties']['body']['background-size'] = 'auto';
                $systemProperties['properties']['content']['padding-right'] = '60px';
                $systemProperties['properties']['site']['tagline']['color'] = '#ffffff';
                $systemProperties['properties']['footer']['letter-spacing'] = '2px';
                $systemProperties['properties']['content']['padding-top'] = '40px';
                $systemProperties['properties']['body']['background-color'] = '';
                $systemProperties['properties']['site']['tagline']['margin-top'] = '20px';
                $systemProperties['properties']['content']['content']['max-width'] = '';
                $systemProperties['properties']['banner']['padding-right'] = '60px';
                $systemProperties['properties']['blockquote']['color'] = '';
                $systemProperties['properties']['banner']['background-color'] = '';
                $systemProperties['properties']['nav']['padding-right'] = '';
                $systemProperties['properties']['nav']['padding-top'] = '5px';
                $systemProperties['properties']['footer']['socialbuttons']['display'] = 'block';
                $systemProperties['properties']['site']['tagline']['text-decoration'] = 'none';
                $systemProperties['properties']['footer']['padding-right'] = '60px';
                $systemProperties['properties']['blockquote']['font-family'] = '';
                $systemProperties['properties']['banner']['background-size'] = 'cover';
                $systemProperties['properties']['body']['padding-top'] = '50px';
                $systemProperties['properties']['footer']['background-color'] = 'rgba(34,34,34,0.80)';
                $systemProperties['properties']['banner']['max-width'] = '960px';
                $systemProperties['properties']['nav']['text-align'] = 'center';
                $systemProperties['properties']['blockquote']['font-size'] = '';
                $systemProperties['properties']['nav']['spacing'] = '20px';
                $systemProperties['properties']['banner']['background-repeat'] = 'no-repeat';
                $systemProperties['properties']['footer']['font-family'] = '\'Open Sans\'';
                $systemProperties['properties']['nav']['padding-bottom'] = '5px';
                $systemProperties['properties']['site']['tagline']['padding-right'] = '';
                $systemProperties['properties']['mobile']['map']['enabled'] = 'true';
                $systemProperties['properties']['mobile']['call']['enabled'] = 'true';
                $systemProperties['properties']['mobile']['header']['font-color'] = '#ffffff';
                $systemProperties['properties']['mobile']['banner']['enabled'] = 'true';
                $systemProperties['properties']['mobile']['header']['background-color'] = '#006699';
    
//Define navigation structure
$systemProperties['system']['site']['navigation'] = array();
$navigation =& $systemProperties['system']['site']['navigation'];

	$currNavEntry =& $navigation[];
	$currNavEntry['name'] = 'Página inicial';
	$currNavEntry['title'] = 'Página inicial';
	$currNavEntry['href'] = 'index.php';

                
	$currNavEntry =& $navigation[];
	$currNavEntry['name'] = 'Contato';
	$currNavEntry['title'] = 'Contato';
	$currNavEntry['href'] = 'contact-us.php';

                
?>